config/routes.rb
Rails.application.routes.draw do

  root to: 'books#index'
  devise_for :users
  resources :users
  resources :book_checkouts
  resources :books do
    resources :comments
  end
  get '/airdrop', to: 'books#airdrop'
  get '/test_index', to: 'books#test_index'
  get '/about', to: 'books#about'
  # get 'books/index'
end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :user, counter_cache: true
  validates :title, presence: true, length: {minimum: 3}
  validates :author, presence: true

  has_attached_file :cover, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :cover, :content_type => /\Aimage\/.*\Z/

  has_many :book_checkouts, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_attached_file :cover
  attr_reader :cover_remote_url

  def cover_remote_url(url_value)
    self.cover = URI.parse(url_value)
    @cover_remote_url = url_value
  end

  def available? # the presenter calls this
    if most_recent_checkout
      most_recent_checkout.returned?
    else
      true
    end
  end

  def children?
    comments.any?
  end

  def most_recent_checkout
    book_checkouts.order('return_deadline desc').first
  end


  private

  def destroy_book_checkouts
    BookCheckout.delete_all "book_id = #{id}"
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :search, :results, :about]
  require 'open-uri'

  def index
    # Fetches top donor/reader
    leaderboards

    @books = Book.order('available desc').map do |book|
      BookPresenter.new(book)
    end
  end

  def airdrop
    @airdrop = Airdrop.new(user: current_user)

    if @airdrop.save
      redirect_to root_path, :notice => "You have a new book!"
    else
      redirect_to root_path, :notice => "Airdrop quota reached."
    end

  end

  def show
    @book = Book.find(params[:id])

    begin
      # fetches GoodReads information
      goodreadsinfo
    rescue
      redirect_to root_path, :alert => "GoodReads couldn't find the associated book."
    end

    rescue ActiveRecord::RecordNotFound
      redirect_to root_url, :alert => "Record not found."
  end


  def new
    @book = current_user.books.build
  end

  def edit
    @book = Book.find(params[:id])
  end

  def create

    @book = current_user.books.build(book_params)
    @book.cover_remote_url(goodreads.book_by_title(@book.title).image_url)
    if @book.save

      redirect_to @book, :notice => "Book Created"
    else
      render 'new'
    end
  end

  def update
    @book = Book.find(params[:id])

    if @book.update(book_params)
      redirect_to @book
    else
      render 'edit'
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy

    redirect_to books_path, :notice => "Book Removed"
  end



 private
    def book_params
      params.require(:book).permit(:title, :author, :book_checkout_user, :cover)

    end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= simple_form_for :book, multipart: true, url: books_path do |f| %>
  <%= f.input :title, label: 'Book Title' %>
  <%= f.input :author %>

  <%= f.button :submit, "Share It!", :class => "round button" %>
<% end %>

app/views/books/_intro.html.erb
<div class="intro-banner fullWidth">
<h1> Welcome to NovelShare Public Libraries! </h1>
<h3> Please hold onto your library Card at all times. </h3>
</div>

app/views/books/about.html.erb
<div class="about-page">
<h1>A GoodReads Clone about Sharing</h1>

<p>The idea was to replicate a sharing economy web-app. I used a very arbitrary product such as books. </p>

<h3>My Goal was to learn a few things</h3>
<ul>
  <li>Relationship between MVC</li>
  <li>ORM, ActiveRecord</li>
  <li>API usage</li>
  <li>Rspec, Capybara </li>
  <li>SQL searching</li>
</ul>

<h3>While reinforcing concepts</h3>
<ul>
  <li>Zurb Foundation Framework/Responsive Design</li>
  <li>Ruby Fundamentals</li>
  <li>Javascript Hover States</li>
  <li>Rails Deployment</li>
  <li>Gems</li>
</ul>

<h1> How to Use </h1>

<p>Users can "share" books that they wish to have others borrow.
It will then be entered to the database as a new book</p>

<p>All shared books are referenced through the GoodReads API. If the API cannot locate the book title, then "showing" a book will not display any information. However the book can still be checked out, returned, and removed</p>

<h1>Features</h1>

<p>BookDrop is a feature that generates a book for the current user. It uses Nokogiri to parse the 'most popular' list of goodreads, fetching a random book from the list using Ruby.</p>

<p>Javascript hover toggles will highlight one of three statuses (Available, unavailable, new) Availibility is based on whether a book is checked out or not. A book is considered "new" so long it is less than 4 days old. </p>

<p>A presenter class is wrapped around each book to give specific class characteristics. This is used to generate the necessary hoverstates for javascript.</p>



</div>

app/views/books/index.html.erb
  <%= render 'intro' %>


<div class="row fullWidth">
  <div class="large-12 columns">
    <h1 id = 'banner'>
    <span class="status-toggles">

      <span class="action"><%= link_to "Share Book", new_book_path %></span>
      <span class='action'><%= link_to "Free Book!", airdrop_path, method: :get %></span>
    </span>
    </h1>
      <div class="large-3 medium-6 hide-for-medium-down columns scoreboard">
        <h1> Stats </h1>
        <% if User.exists? %>
          <h3>Top Donor: <h6><%= @top_donor.username %></h6></h3>
          <h3>Top Bookworm: <h6><%= @bookworm.username %></h6></h3>
        <% end %>

        <h3>Total Books: <%= Book.count %> </h3>
        <h3>Total Users: <%= User.count %> </h3><br>
    <br>
    <br>
      </div>
      <div class ="large-9 medium-12 columns">
      <% @books.each do |book| %>

        <div class="row books">

          <div class="large-12 medium-12 columns index-book <%= book.css_classes %>">

            <div class="large-2 medium-3 small-12 columns">

              <% unless book.cover_file_name==nil%>
                <%= link_to(book_path(book)) do %>
<!--                   <%= image_tag book.cover.url %> -->
                    <%= image_tag book.book_cover_url %>
                <% end %>

              <% else %>

              <div class="book-cover-alt index-book-text">
                <%= link_to book.title, book_path(book) %><br>
                <%= book.author %>
              </div>
              <% end %>

            </div>

            <div class="large-10 medium-9 small-12 columns fixed-width-left">

              <% if current_user == book.user && (book.children? == false)%>
                <%= simple_form_for :comment, url: book_comments_path(book) do |f| %>
                      <%= f.text_area :quote, placeholder: "Leave a note for the next reader"  %>
                      <%= f.submit 'Submit', class: "button" %>
                  <% end %>
              <% else %>
                <% if book.children? %>
                <h3>
                  <%= Comment.where(book_id: book.id).first.quote.html_safe %>
                </h3>
                  - <%= User.find(book.user_id).username %>
                <% end %>
              <% end %>

              <div class="large-12 medium-12 small-12 columns book-buttons">


     <%= simple_form_for :book_checkout, multipart: true, url: book_checkouts_path do |f| %>

          <%= f.hidden_field :checkout_user_id, value: 3 %>
          <%= f.hidden_field :book_id, value: book.id %>
          <% if user_signed_in? %>
            <% if book.user_id == current_user.id && book.checkout_user_id == nil%>
              <%= link_to "Remove", book_path(book), :confirm => 'Works!', :class => "button", :method => :delete %>
            <% end %>
            <% if book.checkout_user_id == nil %>
              <% if book.user_id != current_user.id %>
                <%= f.button :submit, "Checkout"%>
              <% end %>
            <% end %>

            <% if book.checkout_user_id != nil %>

              <% if book.checkout_user_id != current_user.id %>
                <p>Checked out by <%= User.find(book.checkout_user_id).username %></p>
              <% else %>

                <%= link_to "Return", book_checkout_path(id: book.id), :confirm => 'Are you sure?', :class => "button", :method => :delete %>
              <% end %>
            <% end %>
          <% end %>

          <% end %>



            </div>



</div>





            </div> <!-- end index_book -->

          </div> <!-- end book_row -->

          <% end %> <!-- end book loop -->
        </div>







  </div>
</div>

app/views/books/new.html.erb
<div class = "row">
  <div class = "large-8 columns">
  <br>
  <h1> Share a Book </h1>
    <%= render 'form' %>
  </div>
</div>

app/views/books/show.html.erb
<!-- request token template not working properly -->

<div class="row">
  <div class="large-12 columns">

    <!-- client.user_id requires Oauth -->

    <div class="row">

    <div class="large-8 medium-10 columns">
        <div class="panel">

          <%= image_tag @author["image_url"] %>
          <span class="book-show-cover">
          <%= image_tag(@goodreadsbook.image_url, :size => "147x222") %>
          </span>

          <div class= "widget">
            <%= @goodreadsbook.reviews_widget.html_safe %>
          </div>
        </div>
      </div>

    <% unless @goodreadsbook.description.nil? %>
    <div class="large-4 medium-12 columns">

      <h3> <%= @book.title %> </h3><br>
      <h3> Written By: <%= link_to @author["name"], @author["link"] %> </h3>


      <h3> Book Rating </h3>
      <p> <%= @avg_rating %> out of <%= @rating_count%></p>

      <h3> <%= link_to "GoodReads Book Link", @book_link %> </h3>


    </div>

    <% end %>




    </div>
  </div>
</div>

app/views/books/test_index.html.erb
<div class ="large-12 medium-12 columns">
  <% @books.each do |book| %>
    <%= book.title %>
  <% end %>
</div>